export const wordlist = [
  "hi",
  "hello",
  "hi there",
  "hello there",
  "hi people",
  "hello people",
  "hi everyone",
  "hello everyone",
  "hi guys",
  "hello guys",
  "hi fam",
  "hello fam",
  "hi family",
  "hello family",
  "hi shx fam",
  "hello shx fam",
  "hi fellas",
  "hello fellas",
  "good day",
  "good morning",
  "good evening",
  "good night",
  "good day fam",
  "good morning fam",
  "good evening fam",
  "good night fam",
  "good day stronghold",
  "good morning stronghold",
  "good evening stronghold",
  "good night stronghold",
  "good day strongholders",
  "good morning strongholders",
  "good evening strongholders",
  "good night strongholders",
  "good day shx family",
  "good morning shx family",
  "good evening shx family",
  "good night shx family",
  "good day shx fam",
  "good morning shx fam",
  "good evening shx fam",
  "good night shx fam",
  "gm",
  "gn",
  "gm fam",
  "gn fam",
  "gm shx fam",
  "gn shx fam",
  "gm stronghold",
  "gn stronghold",
  "gm strongholders",
  "gn strongholders",
  "morning",
  "evening",
  "night",
  "morning guys",
  "evening guys",
  "night guys",
  "morning strongholders",
  "evening strongholders",
  "night strongholders",
  "what's up",
  "whatsup",
  "wsp",
  "sup",
  "sup shx fam",
  "sup stronghold fam",
  "yo",
  "yo what's up",
  "yo whatsup",
  "yo wsp",
  "yo sup",
  "how are you",
  "hru",
  "bye",
  "bye bye",
  "good bye",
  "goodbye",
  "see you",
  "see ya",
  "see u",
  "later",
  "see you later",
  "see u later",
  "peace",
];
